export enum Department {
  HR = 'HR',
  IT = 'IT',
  ENGINEERING = 'ENGINEERING',
  FINANCE = 'FINANCE',
  MARKETING = 'MARKETING',
  SALES = 'SALES',
  OPERATIONS = 'OPERATIONS',
  LEGAL = 'LEGAL',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
}
